"""empty message

Revision ID: 7d57f30187c0
Revises: 8d273c1c539f
Create Date: 2019-11-02 18:59:45.642226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d57f30187c0'
down_revision = '8d273c1c539f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('date_completed', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('member_count', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'teams', ['team_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'member_count')
    op.drop_column('teams', 'date_completed')
    # ### end Alembic commands ###
