"""empty message

Revision ID: e87f37bf9191
Revises: 9538d3d7e4f4
Create Date: 2019-11-14 00:56:49.504392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87f37bf9191'
down_revision = '9538d3d7e4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('progress', sa.Float(), nullable=True))
    op.add_column('teams', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('teams', 'approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'status')
    op.drop_column('teams', 'progress')
    # ### end Alembic commands ###
